Merging template update 3.1.0
nf-core/molkart pull request #94
Opened 2024-12-12 14:13 UTC by kbestak

Resolved conficts in new 3.1.0 TEMPLATE update

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-12-12 15:28 UTC, kbestak commented
@FloWuenne please add your information in the `nextflow.config` file, lines 270-278.

2025-01-08 02:55 UTC, FloWuenne requested changes
@kbestak Sorry it took so long for me to get to this. As soon as you merge this, I will review the 3.1.1 template update!

2025-01-08 02:55 UTC, FloWuenne commented on nextflow.config
> +            orcid: ''
```suggestion
            name: ' @FloWuenne',
            affiliation: 'Seqera',
            email: 'flowuenne@gmail.com',
            github: '@flowuenne',
            contribution: ['author', 'maintainer'], // List of contribution types ('author', 'maintainer' or 'contributor')
            orcid: '0000-0002-0978-6076'
```

2025-01-08 02:55 UTC, FloWuenne commented on conf/modules.config
> +        //singularity.runOptions = "--bind $HOME:$HOME"
If we are commenting this out, might as well remove it?!
```suggestion
```

2025-01-29 09:31 UTC, kbestak commented
Currently failing due to `/bin/bash: line 10: .command.run: Permission denied` error that is being worked on. I'm updating the PR to cover the template 3.2.0 as well

2025-01-29 10:16 UTC, kbestak commented
@FloWuenne I added your commits and also updated to 3.2.0 as some tests were failing. This PR is ready for review again!

2025-02-06 21:22 UTC, FloWuenne approved these changes
LGTM 🚀

2025-02-07 09:26 UTC, merged